from typing import Literal

DomainLiteral = Literal["economy", "labour", "tourism", "greek_tourism"]

EconomyIndicator = Literal[
    "gdp_eur_hab", "gdp_mio_eur", "gfcf", "gva", "gva_sector_a", 
    "gva_sector_bde", "gva_sector_c", "gva_sector_f", "gva_sector_ghi", 
    "gva_sector_ghij", "gva_sector_j", "gva_sector_k", "gva_sector_klmn", 
    "gva_sector_l", "gva_sector_mn", "gva_sector_opq", "gva_sector_opqrstu", 
    "gva_sector_rstu"
]

LabourIndicator = Literal[
    "contributing_family_members", "deprivation", "empl_rate_ED0-2", 
    "empl_rate_ED3-4", "empl_rate_ED5-8", "employees", "employment_full_time", 
    "employment_full_time_pct", "employment_part_time", "employment_part_time_pct", 
    "fca_epl", "fca_no_epl", "housing", "involuntary_part_time", 
    "involuntary_part_time_pct", "involuntary_temporary", "involuntary_temporary_pct", 
    "labour_force", "long_term_unemployment", "long_term_unemployment_rate", 
    "neets", "neets_pop_prc", "permanent_employment", "permanent_employment_pct", 
    "persons_low_work", "persons_risk_poverty", "sector_a", "sector_a_lq", 
    "sector_a_pct", "sector_bde", "sector_bde_lq", "sector_bde_pct", 
    "sector_c", "sector_c_lq", "sector_c_pct", "sector_f", "sector_f_lq", 
    "sector_f_pct", "sector_g", "sector_g_lq", "sector_g_pct", "sector_h", 
    "sector_h_lq", "sector_h_pct", "sector_i", "sector_i_lq", "sector_i_pct", 
    "sector_jklmnu", "sector_jklmnu_lq", "sector_jklmnu_pct", "sector_opq", 
    "sector_opq_lq", "sector_opq_pct", "sector_rst", "sector_rst_lq", 
    "sector_rst_pct", "self_employed", "self_employed_with_employees", 
    "self_employed_without_employees", "skills_isco_0", "skills_isco_1_3", 
    "skills_isco_1_3_pct", "skills_isco_4_5", "skills_isco_4_5_pct", 
    "skills_isco_6_8", "skills_isco_6_8_pct", "skills_isco_9", 
    "skills_isco_9_pct", "temporary_employment", "temporary_employment_pct", 
    "total_employment", "total_employment_rate", "unemployment", 
    "unemployment_rate", "weekly_hours", "youth_employment", 
    "youth_employment_rate", "youth_long_term_unemployment_rate", 
    "youth_unemployment", "youth_unemployment_rate"
]

TourismIndicator = Literal[
    "arrivals", "arrivals_per_km2", "arrivals_per_person", "bed_places", 
    "bed_places_per_1k_persons", "bed_places_per_km2", "establishments", 
    "establishments_per_1k_persons", "establishments_per_km2", "gfcf_sector_ghi", 
    "nights_spent", "nights_spent_per_km2", "nights_spent_per_person", 
    "short_stay", "short_stay_per_km2", "short_stay_per_person"
]

GreekTourismIndicator = Literal[
    "STR_accommodation_beds", "employment_accommodation_catering", 
    "employment_other", "employment_total", "employment_total_greece", 
    "expenditure_per_overnight_stay", "guest_beds", "guest_beds_per_km2", 
    "guest_beds_per_person", "hotels_avg_duration_of_stay_domestic", 
    "hotels_avg_duration_of_stay_foreign", "hotels_avg_duration_of_stay_total", 
    "hotels_domestic_arrivals", "hotels_domestic_overnights", 
    "hotels_foreign_arrivals", "hotels_foreign_overnights", 
    "hotels_total_arrivals", "hotels_total_arrivals_per_km2", 
    "hotels_total_arrivals_per_person", "hotels_total_overnights", 
    "population", "receipts", "rooms", 
    "short_stay_total_arrivals", "short_stay_total_arrivals_per_km2", 
    "short_stay_total_arrivals_per_person", "short_stay_total_overnights", 
    "turnover_accommodation", "turnover_catering", "turnover_total", "units"
]

# Indicator Descriptions for API Documentation
ECONOMY_DESC = {
    "gdp_eur_hab": "GDP per inhabitant in euros",
    "gdp_mio_eur": "GDP in million euros (absolute)",
    "gfcf": "Gross Fixed Capital Formation, total (absolute)",
    "gva": "Gross Value Added, total in million euros (absolute)",
    "gva_sector_a": "GVA for sector A (Agriculture, forestry and fishing)",
    "gva_sector_bde": "GVA for sectors B-E (Industry except construction)",
    "gva_sector_c": "GVA for sector C (Manufacturing)",
    "gva_sector_f": "GVA for sector F (Construction)",
    "gva_sector_ghij": "GVA for sectors G-J (Trade, transport, accommodation, information)",
    "gva_sector_ghi": "GVA for sectors G-I (Trade, transport, accommodation)",
    "gva_sector_j": "GVA for sector J (Information and communication)",
    "gva_sector_klmn": "GVA for sectors K-N (Financial and business services)",
    "gva_sector_k": "GVA for sector K (Financial and insurance activities)",
    "gva_sector_l": "GVA for sector L (Real estate activities)",
    "gva_sector_mn": "GVA for sectors M-N (Professional, scientific, technical and administrative services)",
    "gva_sector_opq": "GVA for sectors O-Q (Public admin, education, health)",
    "gva_sector_opqrstu": "GVA for sectors O-U (Public services and other)",
    "gva_sector_rstu": "GVA for sectors R-U (Arts, other services, households)"
}

LABOUR_DESC = {
    "contributing_family_members": "Employment as contributing family members",
    "deprivation": "Material deprivation (2021+)",
    "empl_rate_ED0-2": "Employment rate (Educational attainment ED0-2)",
    "empl_rate_ED3-4": "Employment rate (Educational attainment ED3-4)",
    "empl_rate_ED5-8": "Employment rate (Educational attainment ED5-8)",
    "employees": "Total number of employees",
    "employment_full_time": "Total full-time employment",
    "employment_full_time_pct": "Full-time employment as percentage of total",
    "employment_part_time": "Total part-time employment",
    "employment_part_time_pct": "Part-time employment as percentage of total",
    "fca_epl": "Very Fragile Conditional Autonomy rates with EPL",
    "fca_no_epl": "Very Fragile Conditional Autonomy rates without EPL",
    "housing": "Housing conditions (2021+)",
    "involuntary_part_time": "Involuntary part-time employment",
    "involuntary_part_time_pct": "Involuntary part-time employment as percentage of total",
    "involuntary_temporary": "Involuntary temporary employment",
    "involuntary_temporary_pct": "Involuntary temporary employment as percentage of total",
    "labour_force": "Total labour force",
    "long_term_unemployment": "Total long-term unemployment",
    "long_term_unemployment_rate": "Long-term unemployment rate",
    "neets": "Total NEETs (Not in Education, Employment, or Training)",
    "neets_pop_prc": "NEETs as percentage of population (ages 15-29)",
    "permanent_employment": "Total permanent employment",
    "permanent_employment_pct": "Permanent employment as percentage of total",
    "persons_low_work": "Persons living in low work intensity households (2021+)",
    "persons_risk_poverty": "Persons at risk of poverty (2021+)",
    "sector_a": "Employment in Agriculture (Sector A)",
    "sector_a_lq": "Location Quotient for Agriculture (Sector A)",
    "sector_a_pct": "Employment in Agriculture (% of total)",
    "sector_bde": "Employment in Mining, quarrying, power (Sectors B-E)",
    "sector_bde_lq": "Location Quotient for Mining, quarrying, power (Sectors B-E)",
    "sector_bde_pct": "Employment in Mining, quarrying, power (% of total)",
    "sector_c": "Employment in Manufacturing (Sector C)",
    "sector_c_lq": "Location Quotient for Manufacturing (Sector C)",
    "sector_c_pct": "Employment in Manufacturing (% of total)",
    "sector_f": "Employment in Construction (Sector F)",
    "sector_f_lq": "Location Quotient for Construction (Sector F)",
    "sector_f_pct": "Employment in Construction (% of total)",
    "sector_g": "Employment in Commerce (Sector G)",
    "sector_g_lq": "Location Quotient for Commerce (Sector G)",
    "sector_g_pct": "Employment in Commerce (% of total)",
    "sector_h": "Employment in Transportation (Sector H)",
    "sector_h_lq": "Location Quotient for Transportation (Sector H)",
    "sector_h_pct": "Employment in Transportation (% of total)",
    "sector_i": "Employment in Accommodation & catering (Sector I)",
    "sector_i_lq": "Location Quotient for Accommodation & catering (Sector I)",
    "sector_i_pct": "Employment in Accommodation & catering (% of total)",
    "sector_jklmnu": "Employment in Knowledge economy (Sectors J-N)",
    "sector_jklmnu_lq": "Location Quotient for Knowledge economy (Sectors J-N)",
    "sector_jklmnu_pct": "Employment in Knowledge economy (% of total)",
    "sector_opq": "Employment in Public admin, education, healthcare (Sectors O-Q)",
    "sector_opq_lq": "Location Quotient for Public admin, education, healthcare (Sectors O-Q)",
    "sector_opq_pct": "Employment in Public admin, education, healthcare (% of total)",
    "sector_rst": "Employment in Other services (Sectors R-T)",
    "sector_rst_lq": "Location Quotient for Other services (Sectors R-T)",
    "sector_rst_pct": "Employment in Other services (% of total)",
    "self_employed": "Total self-employed persons",
    "self_employed_with_employees": "Self-employed with employees",
    "self_employed_without_employees": "Self-employed without employees",
    "skills_isco_0": "Employment in Skills ISCO 0 (Armed forces)",
    "skills_isco_1_3": "Employment in Skills ISCO 1-3 (High)",
    "skills_isco_1_3_pct": "Skills ISCO 1-3 as percentage of total",
    "skills_isco_4_5": "Employment in Skills ISCO 4-5 (Medium non-manual)",
    "skills_isco_4_5_pct": "Skills ISCO 4-5 as percentage of total",
    "skills_isco_6_8": "Employment in Skills ISCO 6-8 (Medium manual)",
    "skills_isco_6_8_pct": "Skills ISCO 6-8 as percentage of total",
    "skills_isco_9": "Employment in Skills ISCO 9 (Low)",
    "skills_isco_9_pct": "Skills ISCO 9 as percentage of total",
    "temporary_employment": "Total temporary employment",
    "temporary_employment_pct": "Temporary employment as percentage of total",
    "total_employment": "Total employment",
    "total_employment_rate": "Total employment rate",
    "unemployment": "Total unemployment",
    "unemployment_rate": "Total unemployment rate",
    "weekly_hours": "Average weekly hours worked",
    "youth_employment": "Total youth employment (ages 15-29)",
    "youth_employment_rate": "Youth employment rate",
    "youth_long_term_unemployment_rate": "Youth long-term unemployment rate",
    "youth_unemployment": "Total youth unemployment",
    "youth_unemployment_rate": "Youth unemployment rate"
}

TOURISM_DESC = {
    "arrivals": "Arrivals at tourist accommodation establishments, total",
    "arrivals_per_km2": "Arrivals per square kilometer",
    "arrivals_per_person": "Arrivals per capita",
    "bed_places": "Bed-places in tourist accommodation, total",
    "bed_places_per_1k_persons": "Bed-places per 1,000 persons",
    "bed_places_per_km2": "Bed-places per square kilometer",
    "establishments": "Number of tourist accommodation establishments, total",
    "establishments_per_1k_persons": "Establishments per 1,000 persons",
    "establishments_per_km2": "Establishments per square kilometer",
    "gfcf_sector_ghi": "Gross Fixed Capital Formation for NACE sectors G-I, total",
    "nights_spent": "Nights spent at tourist accommodation establishments, total",
    "nights_spent_per_km2": "Nights spent per square kilometer",
    "nights_spent_per_person": "Nights spent per capita",
    "short_stay": "Short-stay nights (collaborative platforms), total",
    "short_stay_per_km2": "Short-stay nights per square kilometer",
    "short_stay_per_person": "Short-stay nights per capita"
}

GREEK_TOURISM_DESC = {
    "STR_accommodation_beds": "Short-term rental accommodation bed capacity",
    "employment_accommodation_catering": "Employment in accommodation & catering sector",
    "employment_other": "Employment in other sectors",
    "employment_total": "Total employment in region",
    "employment_total_greece": "Total employment in Greece (reference)",
    "expenditure_per_overnight_stay": "Average expenditure per overnight stay",
    "guest_beds": "Total number of guest beds",
    "guest_beds_per_km2": "Guest beds per square kilometer",
    "guest_beds_per_person": "Guest beds per capita",
    "hotels_avg_duration_of_stay_domestic": "Average stay duration (Domestic hotel guests)",
    "hotels_avg_duration_of_stay_foreign": "Average stay duration (Foreign hotel guests)",
    "hotels_avg_duration_of_stay_total": "Average stay duration (All hotel guests)",
    "hotels_domestic_arrivals": "Hotel arrivals: Domestic guests",
    "hotels_domestic_overnights": "Hotel overnights: Domestic guests",
    "hotels_foreign_arrivals": "Hotel arrivals: Foreign guests",
    "hotels_foreign_overnights": "Hotel overnights: Foreign guests",
    "hotels_total_arrivals": "Total hotel arrivals",
    "hotels_total_arrivals_per_km2": "Hotel arrivals per square kilometer",
    "hotels_total_arrivals_per_person": "Hotel arrivals per capita",
    "hotels_total_overnights": "Total hotel overnights",
    "population": "Regional population",
    "receipts": "Tourism receipts in million euros",
    "rooms": "Total number of hotel rooms",
    "short_stay_total_arrivals": "Total short-stay arrivals (collaborative economy)",
    "short_stay_total_arrivals_per_km2": "Short-stay arrivals per square kilometer",
    "short_stay_total_arrivals_per_person": "Short-stay arrivals per capita",
    "short_stay_total_overnights": "Total short-stay overnights (collaborative economy)",
    "turnover_accommodation": "Turnover in accommodation services",
    "turnover_catering": "Turnover in catering services",
    "turnover_total": "Total tourism industry turnover",
    "units": "Number of hotel units"
}

# Domain-Specific NUTS 2 Codes based on exhaustive mega-audit of all indicators
EconomyNutsCode = Literal[
    'AL01', 'AL02', 'AL03', 'AT11', 'AT12', 'AT13', 'AT21', 'AT22', 'AT31', 'AT32', 'AT33', 'AT34', 'ATZZ', 
    'BE10', 'BE21', 'BE22', 'BE23', 'BE24', 'BE25', 'BE31', 'BE32', 'BE33', 'BE34', 'BE35', 'BEZZ', 
    'BG31', 'BG32', 'BG33', 'BG34', 'BG41', 'BG42', 'BGZZ', 'CH01', 'CH02', 'CH03', 'CH04', 'CH05', 'CH06', 'CH07', 
    'CY00', 'CYZZ', 'CZ01', 'CZ02', 'CZ03', 'CZ04', 'CZ05', 'CZ06', 'CZ07', 'CZ08', 'CZZZ', 
    'DE11', 'DE12', 'DE13', 'DE14', 'DE21', 'DE22', 'DE23', 'DE24', 'DE25', 'DE26', 'DE27', 'DE30', 'DE40', 
    'DE50', 'DE60', 'DE71', 'DE72', 'DE73', 'DE80', 'DE91', 'DE92', 'DE93', 'DE94', 
    'DEA1', 'DEA2', 'DEA3', 'DEA4', 'DEA5', 'DEB1', 'DEB2', 'DEB3', 'DEC0', 'DED2', 'DED4', 'DED5', 
    'DEE0', 'DEF0', 'DEG0', 'DEZZ', 'DK01', 'DK02', 'DK03', 'DK04', 'DK05', 'DKZZ', 'EE00', 'EEZZ', 
    'EL30', 'EL41', 'EL42', 'EL43', 'EL51', 'EL52', 'EL53', 'EL54', 'EL61', 'EL62', 'EL63', 'EL64', 'EL65', 'ELZZ', 
    'ES11', 'ES12', 'ES13', 'ES21', 'ES22', 'ES23', 'ES24', 'ES30', 'ES41', 'ES42', 'ES43', 'ES51', 'ES52', 'ES53', 
    'ES61', 'ES62', 'ES63', 'ES64', 'ES70', 'ESZZ', 'FI19', 'FI1B', 'FI1C', 'FI1D', 'FI20', 'FIZZ', 
    'FR10', 'FRB0', 'FRC1', 'FRC2', 'FRD1', 'FRD2', 'FRE1', 'FRE2', 'FRF1', 'FRF2', 'FRF3', 'FRG0', 'FRH0', 
    'FRI1', 'FRI2', 'FRI3', 'FRJ1', 'FRJ2', 'FRK1', 'FRK2', 'FRL0', 'FRM0', 'FRY1', 'FRY2', 'FRY3', 'FRY4', 'FRY5', 'FRZZ', 
    'HR02', 'HR03', 'HR05', 'HR06', 'HRZZ', 'HU11', 'HU12', 'HU21', 'HU22', 'HU23', 'HU31', 'HU32', 'HU33', 'HUZZ', 
    'IE04', 'IE05', 'IE06', 'IEZZ', 'ITC1', 'ITC2', 'ITC3', 'ITC4', 'ITF1', 'ITF2', 'ITF3', 'ITF4', 'ITF5', 'ITF6', 
    'ITG1', 'ITG2', 'ITH1', 'ITH2', 'ITH3', 'ITH4', 'ITH5', 'ITI1', 'ITI2', 'ITI3', 'ITI4', 'ITZZ', 
    'LT01', 'LT02', 'LU00', 'LV00', 'LVZZ', 'ME00', 'MK00', 'MT00', 'MTZZ', 
    'NL11', 'NL12', 'NL13', 'NL21', 'NL22', 'NL23', 'NL32', 'NL34', 'NL41', 'NL42', 'NLZZ', 
    'NO02', 'NO06', 'NO07', 'NO08', 'NO09', 'NO0A', 'NO0B', 'NOZZ', 
    'PL21', 'PL22', 'PL41', 'PL42', 'PL43', 'PL51', 'PL52', 'PL61', 'PL62', 'PL63', 'PL71', 'PL72', 'PL81', 'PL82', 'PL84', 'PL91', 'PL92', 'PLZZ', 
    'PT11', 'PT15', 'PT20', 'PT30', 'PTZZ', 'RO11', 'RO12', 'RO21', 'RO22', 'RO31', 'RO32', 'RO41', 'RO42', 'ROZZ', 
    'RS11', 'RS12', 'RS21', 'RS22', 'RSZZ', 'SE11', 'SE12', 'SE21', 'SE22', 'SE23', 'SE31', 'SE32', 'SE33', 'SEZZ', 
    'SI03', 'SI04', 'SK01', 'SK02', 'SK03', 'SK04', 
    'TR10', 'TR21', 'TR22', 'TR31', 'TR32', 'TR33', 'TR41', 'TR42', 'TR51', 'TR52', 'TR61', 'TR62', 'TR63', 'TR71', 'TR72', 'TR81', 'TR82', 'TR83', 'TR90', 
    'TRA1', 'TRA2', 'TRB1', 'TRB2', 'TRC1', 'TRC2', 'TRC3'
]

LabourNutsCode = Literal[
    'AL01', 'AL02', 'AL03', 
    'AT11', 'AT12', 'AT13', 'AT21', 'AT22', 'AT31', 'AT32', 'AT33', 'AT34', 
    'BE10', 'BE21', 'BE22', 'BE23', 'BE24', 'BE25', 'BE31', 'BE32', 'BE33', 'BE34', 'BE35', 
    'BG31', 'BG32', 'BG33', 'BG34', 'BG41', 'BG42', 'CH01', 'CH02', 'CH03', 'CH04', 'CH05', 'CH06', 'CH07', 
    'CY00', 'CZ01', 'CZ02', 'CZ03', 'CZ04', 'CZ05', 'CZ06', 'CZ07', 'CZ08', 
    'DE11', 'DE12', 'DE13', 'DE14', 'DE21', 'DE22', 'DE23', 'DE24', 'DE25', 'DE26', 'DE27', 'DE30', 
    'DE40', 'DE50', 'DE60', 'DE71', 'DE72', 'DE73', 'DE80', 'DE91', 'DE92', 'DE93', 'DE94', 
    'DEA1', 'DEA2', 'DEA3', 'DEA4', 'DEA5', 'DEB1', 'DEB2', 'DEB3', 'DEC0', 'DED2', 'DED4', 'DED5', 
    'DEE0', 'DEF0', 'DEG0', 'DK01', 'DK02', 'DK03', 'DK04', 'DK05', 'EE00', 
    'EL30', 'EL41', 'EL42', 'EL43', 'EL51', 'EL52', 'EL53', 'EL54', 'EL61', 'EL62', 'EL63', 'EL64', 'EL65', 
    'ES11', 'ES12', 'ES13', 'ES21', 'ES22', 'ES23', 'ES24', 'ES30', 'ES41', 'ES42', 'ES43', 'ES51', 'ES52', 'ES53', 
    'ES61', 'ES62', 'ES63', 'ES64', 'ES70', 'FI18', 'FI19', 'FI1B', 'FI1C', 'FI1D', 'FI20', 
    'FR10', 'FR21', 'FR22', 'FR23', 'FR24', 'FR25', 'FR26', 'FR30', 'FR41', 'FR42', 'FR43', 'FR51', 'FR52', 'FR53', 'FR61', 'FR62', 'FR63', 'FR71', 'FR72', 'FR81', 'FR82', 'FR83', 
    'FRB0', 'FRC1', 'FRC2', 'FRD1', 'FRD2', 'FRE1', 'FRE2', 'FRF1', 'FRF2', 'FRF3', 'FRG0', 'FRH0', 
    'FRI1', 'FRI2', 'FRI3', 'FRJ1', 'FRJ2', 'FRK1', 'FRK2', 'FRL0', 'FRM0', 'FRY1', 'FRY2', 'FRY3', 'FRY4', 'FRY5', 
    'HR02', 'HR03', 'HR04', 'HR05', 'HR06', 'HU10', 'HU11', 'HU12', 'HU21', 'HU22', 'HU23', 'HU31', 'HU32', 'HU33', 
    'IE01', 'IE02', 'IE04', 'IE05', 'IE06', 'IS00', 'ITC1', 'ITC2', 'ITC3', 'ITC4', 'ITF1', 'ITF2', 'ITF3', 'ITF4', 'ITF5', 'ITF6', 
    'ITG1', 'ITG2', 'ITH1', 'ITH2', 'ITH3', 'ITH4', 'ITH5', 'ITI1', 'ITI2', 'ITI3', 'ITI4', 
    'LT00', 'LT01', 'LT02', 'LU00', 'LV00', 'ME00', 'MK00', 'MT00', 
    'NL11', 'NL12', 'NL13', 'NL21', 'NL22', 'NL23', 'NL31', 'NL32', 'NL33', 'NL34', 'NL41', 'NL42', 
    'NO02', 'NO06', 'NO07', 'NO08', 'NO09', 'NO0A', 
    'PL11', 'PL12', 'PL21', 'PL22', 'PL31', 'PL32', 'PL33', 'PL34', 'PL41', 'PL42', 'PL43', 'PL51', 'PL52', 'PL61', 'PL62', 'PL63', 'PL71', 'PL72', 'PL81', 'PL82', 'PL84', 'PL91', 'PL92', 
    'PT11', 'PT15', 'PT16', 'PT17', 'PT18', 'PT20', 'PT30', 'RO11', 'RO12', 'RO21', 'RO22', 'RO31', 'RO32', 'RO41', 'RO42', 
    'RS11', 'RS12', 'RS21', 'RS22', 'SE11', 'SE12', 'SE21', 'SE22', 'SE23', 'SE31', 'SE32', 'SE33', 
    'SI01', 'SI02', 'SI03', 'SI04', 'SK01', 'SK02', 'SK03', 'SK04', 
    'TR10', 'TR21', 'TR22', 'TR31', 'TR32', 'TR33', 'TR41', 'TR42', 'TR51', 'TR52', 'TR61', 'TR62', 'TR63', 'TR71', 'TR72', 'TR81', 'TR82', 'TR83', 'TR90', 
    'TRA1', 'TRA2', 'TRB1', 'TRB2', 'TRC1', 'TRC2', 'TRC3', 
    'UKC1', 'UKC2', 'UKD1', 'UKD3', 'UKD4', 'UKD6', 'UKD7', 'UKE1', 'UKE2', 'UKE3', 'UKE4', 'UKF1', 'UKF2', 'UKF3', 'UKG1', 'UKG2', 'UKG3', 'UKH1', 'UKH2', 'UKH3', 'UKI1', 'UKI2', 'UKI3', 'UKI4', 'UKI5', 'UKI6', 'UKI7', 'UKJ1', 'UKJ2', 'UKJ3', 'UKJ4', 'UKK1', 'UKK2', 'UKK3', 'UKK4', 'UKL1', 'UKL2', 'UKM2', 'UKM3', 'UKM5', 'UKM6', 'UKM7', 'UKM8', 'UKM9', 'UKN0'
]

TourismNutsCode = Literal[
    'AL01', 'AL02', 'AL03', 'AT11', 'AT12', 'AT13', 'AT21', 'AT22', 'AT31', 'AT32', 'AT33', 'AT34', 'ATZZ', 
    'BE10', 'BE21', 'BE22', 'BE23', 'BE24', 'BE25', 'BE31', 'BE32', 'BE33', 'BE34', 'BE35', 
    'BG31', 'BG32', 'BG33', 'BG34', 'BG41', 'BG42', 'CH01', 'CH02', 'CH03', 'CH04', 'CH05', 'CH06', 'CH07', 
    'CY00', 'CZ01', 'CZ02', 'CZ03', 'CZ04', 'CZ05', 'CZ06', 'CZ07', 'CZ08', 
    'DE11', 'DE12', 'DE13', 'DE14', 'DE21', 'DE22', 'DE23', 'DE24', 'DE25', 'DE26', 'DE27', 'DE30', 
    'DE40', 'DE50', 'DE60', 'DE71', 'DE72', 'DE73', 'DE80', 'DE91', 'DE92', 'DE93', 'DE94', 
    'DEA1', 'DEA2', 'DEA3', 'DEA4', 'DEA5', 'DEB1', 'DEB2', 'DEB3', 'DEC0', 'DED2', 'DED4', 'DED5', 
    'DEE0', 'DEF0', 'DEG0', 'DK01', 'DK02', 'DK03', 'DK04', 'DK05', 'DKZZ', 'EE00', 
    'EL30', 'EL41', 'EL42', 'EL43', 'EL51', 'EL52', 'EL53', 'EL54', 'EL61', 'EL62', 'EL63', 'EL64', 'EL65', 
    'ES11', 'ES12', 'ES13', 'ES21', 'ES22', 'ES23', 'ES24', 'ES30', 'ES41', 'ES42', 'ES43', 'ES51', 'ES52', 'ES53', 
    'ES61', 'ES62', 'ES63', 'ES64', 'ES70', 'FI19', 'FI1B', 'FI1C', 'FI1D', 'FI20', 
    'FR10', 'FR21', 'FR22', 'FR23', 'FR24', 'FR25', 'FR26', 'FR3', 'FR30', 'FR41', 'FR42', 'FR43', 
    'FR51', 'FR52', 'FR53', 'FR61', 'FR62', 'FR63', 'FR71', 'FR72', 'FR81', 'FR82', 'FR83', 
    'FRA1', 'FRA2', 'FRA3', 'FRA4', 'FRA5', 'FRB0', 'FRC1', 'FRC2', 'FRD1', 'FRD2', 'FRE1', 'FRE2', 
    'FRF1', 'FRF2', 'FRF3', 'FRG0', 'FRH0', 'FRI1', 'FRI2', 'FRI3', 'FRJ1', 'FRJ2', 'FRK1', 'FRK2', 'FRL0', 'FRM0', 'FRY1', 'FRY2', 'FRY3', 'FRY4', 'FRY5', 
    'HR02', 'HR03', 'HR04', 'HR05', 'HR06', 'HU10', 'HU11', 'HU12', 'HU21', 'HU22', 'HU23', 'HU31', 'HU32', 'HU33', 
    'IE01', 'IE02', 'IE04', 'IE05', 'IE06', 'IS00', 'ITC1', 'ITC2', 'ITC3', 'ITC4', 'ITF1', 'ITF2', 'ITF3', 'ITF4', 'ITF5', 'ITF6', 
    'ITG1', 'ITG2', 'ITH1', 'ITH2', 'ITH3', 'ITH4', 'ITH5', 'ITI1', 'ITI2', 'ITI3', 'ITI4', 
    'LI00', 'LT00', 'LT01', 'LT02', 'LU00', 'LV00', 'ME00', 'MK00', 'MT00', 
    'NL11', 'NL12', 'NL13', 'NL21', 'NL22', 'NL23', 'NL31', 'NL32', 'NL33', 'NL34', 'NL41', 'NL42', 
    'NO02', 'NO06', 'NO07', 'NO08', 'NO09', 'NO0A', 'NO0B', 
    'PL11', 'PL12', 'PL21', 'PL22', 'PL31', 'PL32', 'PL33', 'PL34', 'PL41', 'PL42', 'PL43', 'PL51', 'PL52', 'PL61', 'PL62', 'PL63', 'PL71', 'PL72', 'PL81', 'PL82', 'PL84', 'PL91', 'PL92', 
    'PT11', 'PT15', 'PT16', 'PT17', 'PT18', 'PT20', 'PT30', 'RO11', 'RO12', 'RO21', 'RO22', 'RO31', 'RO32', 'RO41', 'RO42', 
    'RS11', 'RS12', 'RS21', 'RS22', 'SE11', 'SE12', 'SE21', 'SE22', 'SE23', 'SE31', 'SE32', 'SE33', 
    'SI03', 'SI04', 'SK01', 'SK02', 'SK03', 'SK04', 
    'TR10', 'TR21', 'TR22', 'TR31', 'TR32', 'TR33', 'TR41', 'TR42', 'TR51', 'TR52', 'TR61', 'TR62', 'TR63', 'TR71', 'TR72', 'TR81', 'TR82', 'TR83', 'TR90', 
    'TRA1', 'TRA2', 'TRB1', 'TRB2', 'TRC1', 'TRC2', 'TRC3', 
    'UKC1', 'UKC2', 'UKD1', 'UKD3', 'UKD4', 'UKD6', 'UKD7', 'UKE1', 'UKE2', 'UKE3', 'UKE4', 'UKF1', 'UKF2', 'UKF3', 'UKG1', 'UKG2', 'UKG3', 'UKH1', 'UKH2', 'UKH3', 'UKI1', 'UKI2', 'UKI3', 'UKI4', 'UKI5', 'UKI6', 'UKI7', 'UKJ1', 'UKJ2', 'UKJ3', 'UKJ4', 'UKK1', 'UKK2', 'UKK3', 'UKK4', 'UKL1', 'UKL2', 'UKM2', 'UKM3', 'UKM5', 'UKM6', 'UKN0'
]

GreekTourismNutsCode = Literal[
    'EL30', 'EL41', 'EL42', 'EL43', 'EL51', 'EL52', 'EL53', 'EL54', 'EL61', 'EL62', 'EL63', 'EL64', 'EL65'
]
